import React, { useCallback, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";

import { inventoryService } from "../../application/inventory-service";
import type { BackupPackage } from "../../core/backup/backup-service";
import { colors, radius, spacing, typography } from "../../theme/tokens";
import { formatDate } from "../../utils/format";
import { AppButton } from "../components/app-button";
import { useFocusLoad } from "../hooks/use-focus-load";
import { useDialog } from "../context/dialog";
import { useInterfaceSettings } from "../context/interface-settings";

export function BackupScreen() {
  const { refresh: refreshInterfaceSettings } = useInterfaceSettings();
  const { confirm, alert } = useDialog();
  const loader = useCallback(() => inventoryService.getSettings(), []);
  const { data: settings, refresh } = useFocusLoad(loader);
  const [busy, setBusy] = useState(false); const [candidate, setCandidate] = useState<BackupPackage | null>(null);
  const create = async () => { setBusy(true); try { const result = await inventoryService.createBackup(true); await Promise.all([refresh(), refreshInterfaceSettings()]); void alert({ title: "Respaldo creado", message: `${result.itemCount} prendas, ${result.locationCount} ubicaciones y ${result.photoCount} fotos.`, icon: "cloud-check-outline" }); } catch (error) { void alert({ title: "No pudimos crear el respaldo", message: error instanceof Error ? error.message : "No se creó ningún archivo.", tone: "danger" }); } finally { setBusy(false); } };
  const select = async () => { setBusy(true); try { const backup = await inventoryService.pickBackup(); setCandidate(backup); } catch (error) { void alert({ title: "Respaldo no válido", message: error instanceof Error ? error.message : "Seleccione otro archivo.", tone: "danger" }); } finally { setBusy(false); } };
  const restore = async () => { if (!candidate) return; const itemCount = candidate.tables.items.length; if (!(await confirm({ title: "Restaurar respaldo", message: `Se reemplazarán los datos actuales por ${itemCount} prendas del respaldo. Primero se validará el paquete y se creará un respaldo completo de seguridad.`, confirmLabel: "Restaurar", tone: "danger", icon: "backup-restore" }))) return; setBusy(true); try { await inventoryService.restoreBackup(candidate); setCandidate(null); await Promise.all([refresh(), refreshInterfaceSettings()]); void alert({ title: "Restauración finalizada", message: "Los datos y las fotografías quedaron restaurados.", icon: "check-circle-outline" }); } catch (error) { void alert({ title: "No pudimos restaurar", message: error instanceof Error ? error.message : "Los datos y fotos anteriores se conservaron.", tone: "danger" }); } finally { setBusy(false); } };
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.notice}><MaterialCommunityIcons name="cellphone-lock" size={32} color={colors.primary} /><View style={styles.noticeCopy}><Text style={styles.noticeTitle}>Datos locales</Text><Text style={styles.text}>Cada dispositivo conserva su propia copia hasta implementar sincronización con Django. Guarde respaldos fuera del teléfono.</Text></View></View><View style={styles.card}><Text style={styles.title}>Crear respaldo</Text><Text style={styles.text}>Incluye inventario, ubicaciones, historial, ajustes y fotografías en un paquete validado.</Text><Text style={styles.meta}>Último respaldo: {formatDate(settings?.lastBackupAt ?? null)}</Text><AppButton label={busy ? "Procesando..." : "Crear y compartir respaldo"} icon="cloud-upload-outline" onPress={() => void create()} disabled={busy} /></View><View style={styles.card}><Text style={styles.title}>Restaurar respaldo</Text><Text style={styles.text}>El archivo se valida por versión e integridad antes de mostrar la confirmación. Nunca se sobrescribe silenciosamente.</Text><AppButton tone="secondary" label="Seleccionar archivo" icon="file-search-outline" onPress={() => void select()} disabled={busy} />{candidate ? <View style={styles.candidate}><MaterialCommunityIcons name="file-check-outline" size={26} color={colors.success} /><View style={styles.candidateCopy}><Text style={styles.candidateTitle}>Respaldo válido</Text><Text style={styles.meta}>{candidate.tables.items.length} prendas · {candidate.tables.locations.length - 1} ubicaciones · {candidate.photos.length} fotos</Text><Text style={styles.meta}>{formatDate(candidate.createdAt)}</Text></View><AppButton tone="danger" label="Restaurar" icon="backup-restore" onPress={() => void restore()} disabled={busy} /></View> : null}</View><View style={styles.warning}><MaterialCommunityIcons name="alert-circle-outline" size={24} color={colors.danger} /><Text style={styles.warningText}>No borre las fotos ni el archivo de base de datos manualmente. Use siempre esta pantalla para respaldar o restaurar.</Text></View></ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: 100, gap: spacing.lg, backgroundColor: colors.canvas }, notice: { flexDirection: "row", gap: spacing.md, padding: spacing.lg, borderRadius: radius.xl, backgroundColor: colors.tint }, noticeCopy: { flex: 1, gap: spacing.xs }, noticeTitle: { color: colors.textPrimary, fontSize: typography.title, fontWeight: "900" }, text: { color: colors.textMuted, fontSize: typography.body, lineHeight: 22 }, card: { gap: spacing.md, padding: spacing.lg, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, title: { color: colors.textPrimary, fontSize: typography.h2, fontWeight: "900" }, meta: { color: colors.textSecondary, fontSize: typography.small, fontWeight: "700" }, candidate: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: spacing.md, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.tint }, candidateCopy: { flex: 1, minWidth: 180 }, candidateTitle: { color: colors.success, fontWeight: "900" }, warning: { flexDirection: "row", gap: spacing.md, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.dangerSoft }, warningText: { flex: 1, color: colors.danger, lineHeight: 20, fontWeight: "700" } });
