import React, { useCallback, useState } from "react";
import { Modal, StyleSheet, Text, TextInput, View } from "react-native";
import { type BarcodeScanningResult, CameraView, useCameraPermissions } from "expo-camera";
import { router, useLocalSearchParams } from "expo-router";

import { inventoryService } from "../../application/inventory-service";
import type { PhysicalCountLine } from "../../domain/models";
import { colors, inputStyle, radius, spacing, typography } from "../../theme/tokens";
import { AppButton } from "../components/app-button";
import { KeyboardAwareScreen } from "../components/keyboard-aware-screen";
import { ScreenState } from "../components/screen-state";
import { useDialog } from "../context/dialog";
import { useFocusLoad } from "../hooks/use-focus-load";

export function PhysicalCountScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const countId = Number(id); const [permission, requestPermission] = useCameraPermissions();
  const loader = useCallback(() => inventoryService.getPhysicalCount(countId), [countId]); const { data, loading, error, refresh } = useFocusLoad(loader);
  const { alert } = useDialog();
  const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("Escanee la primera prenda."); const [closeKind, setCloseKind] = useState<"finish" | "cancel" | null>(null);
  const scan = async (value: string) => { if (!value.trim() || busy || data?.status !== "open") return; setBusy(true); try { const resolution = await inventoryService.resolveCode(value); if (resolution.type !== "item") { setMessage(resolution.type === "location" ? "Ese código corresponde a una ubicación." : "Código desconocido."); return; } const result = await inventoryService.scanPhysicalCount(countId, resolution.item.id); setMessage(result === "matched" ? `${resolution.item.code}: coincide con la ubicación.` : `${resolution.item.code}: pieza extra, supera lo esperado aquí.`); setCode(""); await refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "No se pudo registrar la lectura."); } finally { setBusy(false); } };
  const close = async () => { if (!closeKind) return; setBusy(true); try { await (closeKind === "finish" ? inventoryService.finishPhysicalCount(countId) : inventoryService.cancelPhysicalCount(countId)); setCloseKind(null); await refresh(); } catch (reason) { void alert({ title: "No pudimos cerrar el conteo", message: reason instanceof Error ? reason.message : "Intente nuevamente.", tone: "danger" }); } finally { setBusy(false); } };
  if (!data && loading) return <ScreenState loading title="Cargando conteo" />;
  if (!data) return <ScreenState title="No pudimos abrir el conteo" body={error ?? undefined} action={<AppButton label="Reintentar" icon="reload" onPress={() => void refresh()} />} />;
  return <KeyboardAwareScreen contentContainerStyle={styles.content}>
    <View style={styles.summary}><Text style={styles.title}>{data.status === "open" ? "Conteo en curso" : data.status === "completed" ? "Conteo finalizado" : "Conteo cancelado"}</Text><Text style={styles.metric}>{data.scannedCount} piezas leídas de {data.expectedCount} esperadas</Text><Text accessibilityLiveRegion="polite" style={styles.message}>{message}</Text></View>
    {data.status === "open" ? <><View style={styles.camera}>{permission?.granted ? <CameraView style={StyleSheet.absoluteFill} onBarcodeScanned={busy ? undefined : ({ data: value }: BarcodeScanningResult) => void scan(value)} barcodeScannerSettings={{ barcodeTypes: ["qr", "code128", "code39", "ean13"] }} /> : <View style={styles.permission}><Text style={styles.text}>Permita la cámara o use la entrada manual.</Text><AppButton label="Permitir cámara" icon="camera-outline" onPress={() => void requestPermission()} /></View>}</View><View style={styles.manual}><TextInput accessibilityLabel="Código de prenda" value={code} onChangeText={setCode} onSubmitEditing={() => void scan(code)} autoCapitalize="characters" placeholder="Código de prenda" maxFontSizeMultiplier={1.4} style={styles.input} /><AppButton label="Registrar" icon="plus" onPress={() => void scan(code)} disabled={!code.trim() || busy} /></View></> : null}
    <CountGroup title={`Coinciden (${data.matchedPieces})`} lines={data.matched} empty="Todavía no hay coincidencias." /><CountGroup title={`Extras (${data.unexpectedPieces})`} lines={data.unexpected} empty="No se encontraron piezas extra." danger /><CountGroup title={`Faltantes (${data.missingPieces})`} lines={data.missing} empty="No quedan piezas faltantes." danger />
    {data.status === "open" ? <View style={styles.actions}><AppButton grow label="Finalizar conteo" icon="check-circle-outline" onPress={() => setCloseKind("finish")} /><AppButton grow tone="danger" label="Cancelar conteo" icon="close-circle-outline" onPress={() => setCloseKind("cancel")} /></View> : <AppButton label="Volver a la ubicación" icon="arrow-left" onPress={() => router.replace({ pathname: "/locations/[id]", params: { id: String(data.locationId) } })} />}
    <Modal visible={closeKind != null} transparent animationType="fade" onRequestClose={() => setCloseKind(null)}><View style={styles.backdrop}><View style={styles.modal}><Text style={styles.modalTitle}>{closeKind === "finish" ? "Finalizar conteo" : "Cancelar conteo"}</Text><Text style={styles.text}>{closeKind === "finish" ? "Se guardarán los faltantes y extras encontrados. El inventario no se moverá automáticamente." : "Las lecturas se conservarán como conteo cancelado."}</Text><View style={styles.actions}><AppButton grow tone="quiet" label="Volver" icon="arrow-left" onPress={() => setCloseKind(null)} /><AppButton grow tone={closeKind === "cancel" ? "danger" : "primary"} label={closeKind === "finish" ? "Confirmar finalización" : "Confirmar cancelación"} icon={closeKind === "finish" ? "check" : "close"} onPress={() => void close()} disabled={busy} /></View></View></View></Modal>
  </KeyboardAwareScreen>;
}

function CountGroup({ title, lines, empty, danger = false }: { title: string; lines: PhysicalCountLine[]; empty: string; danger?: boolean }) { return <View style={styles.group}><Text style={[styles.groupTitle, danger && styles.danger]}>{title}</Text>{lines.length ? lines.map(({ item, pieces }) => <View key={item.id} style={styles.row}><Text style={styles.itemCode}>{item.code}{pieces > 1 ? ` · ${pieces} piezas` : ""}</Text><Text style={styles.text}>{item.currentLocation?.name ?? "Sin asignar"}</Text></View>) : <Text style={styles.text}>{empty}</Text>}</View>; }

const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: 100, gap: spacing.md, backgroundColor: colors.canvas }, summary: { gap: spacing.sm, padding: spacing.lg, borderRadius: radius.xl, backgroundColor: colors.primary }, title: { color: colors.onPrimary, fontSize: typography.h2, fontWeight: "900" }, metric: { color: colors.onPrimary, fontSize: typography.title, fontWeight: "800" }, message: { color: colors.tintStrong, lineHeight: 21 }, camera: { height: 240, overflow: "hidden", borderRadius: radius.xl, backgroundColor: colors.dark }, permission: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.md, padding: spacing.lg, backgroundColor: colors.tint }, manual: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, input: { ...inputStyle, flex: 1, minWidth: 180 }, group: { gap: spacing.sm, padding: spacing.lg, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, groupTitle: { color: colors.success, fontSize: typography.title, fontWeight: "900" }, danger: { color: colors.danger }, row: { minHeight: 48, justifyContent: "center", paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border }, itemCode: { color: colors.textPrimary, fontWeight: "900" }, text: { color: colors.textMuted }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, backdrop: { flex: 1, alignItems: "center", justifyContent: "center", padding: spacing.lg, backgroundColor: colors.overlay }, modal: { width: "100%", maxWidth: 520, gap: spacing.md, padding: spacing.xl, borderRadius: radius.xl, backgroundColor: colors.surface }, modalTitle: { color: colors.textPrimary, fontSize: typography.h2, fontWeight: "900" } });
