import React, { useEffect, useRef, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { CameraView, useCameraPermissions, type BarcodeScanningResult } from "expo-camera";
import * as Haptics from "expo-haptics";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";

import { inventoryService } from "../../application/inventory-service";
import { DuplicateScanLock } from "../../core/scanner/duplicate-lock";
import type { Item, LocationSummary, TransferResult } from "../../domain/models";
import { colors, inputStyle, radius, spacing, typography } from "../../theme/tokens";
import { formatMoney } from "../../utils/format";
import { AppButton } from "../components/app-button";
import { FilterChip } from "../components/filter-chip";
import { KeyboardAwareScreen } from "../components/keyboard-aware-screen";
import { useDialog } from "../context/dialog";

export function TransferScreen() {
  const params = useLocalSearchParams<{ ids?: string; sourceId?: string; destinationId?: string }>();
  const { alert } = useDialog();
  const [permission, requestPermission] = useCameraPermissions(); const [torch, setTorch] = useState(false); const [locations, setLocations] = useState<LocationSummary[]>([]); const [destination, setDestination] = useState<LocationSummary | null>(null); const [items, setItems] = useState<Item[]>([]); const [rejections, setRejections] = useState<string[]>([]); const [manual, setManual] = useState(""); const [busy, setBusy] = useState(false); const [result, setResult] = useState<TransferResult | null>(null); const [lastItem, setLastItem] = useState<Item | null>(null); const lock = useRef(new DuplicateScanLock(1200));

  useEffect(() => { void (async () => { const rows = await inventoryService.listLocations(); setLocations(rows); if (params.destinationId) setDestination(rows.find((location) => location.id === Number(params.destinationId)) ?? null); let initial: Item[] = []; if (params.ids) initial = await inventoryService.getItems(params.ids.split(",").map(Number).filter(Number.isFinite)); else if (params.sourceId) initial = await inventoryService.locationItems(Number(params.sourceId)); const accepted: Item[] = []; const rejected: string[] = []; for (const item of initial) { if (item.status === "sold") rejected.push(`${item.code}: está vendida`); else { accepted.push(item); setLastItem(item); } } setItems(accepted); setRejections(rejected); })(); }, [params.destinationId, params.ids, params.sourceId]);

  const selectDestination = (location: LocationSummary) => { setDestination(location); setItems((current) => current.filter((item) => { if ((item.currentLocationId ?? -1) === location.id) { setRejections((existing) => [...existing, `${item.code}: ya está en ${location.name}`]); return false; } return true; })); };
  const resolve = async (value: string) => { const code = value.trim(); if (!code || busy || !lock.current.accept(code)) return; setBusy(true); try { const resolution = await inventoryService.resolveCode(code); if (!destination) { if (resolution.type !== "location") { setRejections((current) => [`${code}: primero escanee una ubicación destino`, ...current]); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning); return; } selectDestination(resolution.location); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); return; } if (resolution.type !== "item") { setRejections((current) => [`${code}: no corresponde a una prenda`, ...current]); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning); return; } const item = resolution.item; let reason: string | null = null; if (item.status === "sold") reason = "está vendida"; else if (items.some((candidate) => candidate.id === item.id)) reason = "ya fue agregada"; else if ((item.currentLocationId ?? -1) === destination.id) reason = `ya está en ${destination.name}`; if (reason) { setRejections((current) => [`${item.code}: ${reason}`, ...current]); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning); return; } setItems((current) => [...current, item]); setLastItem(item); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } catch (error) { setRejections((current) => [`${code}: ${error instanceof Error ? error.message : "no se pudo leer"}`, ...current]); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error).catch(() => undefined); } finally { setBusy(false); } };
  const finish = async () => { if (!destination || items.length === 0) return; setBusy(true); try { setResult(await inventoryService.moveItems(items.map((item) => item.id), destination.id)); } catch (error) { void alert({ title: "No pudimos finalizar el traslado", message: error instanceof Error ? error.message : "No se modificó ninguna prenda.", tone: "danger" }); } finally { setBusy(false); } };
  const undo = async () => { if (!result) return; try { await inventoryService.undoTransfer(result.batchId); await alert({ title: "Traslado deshecho", message: "Las prendas volvieron a sus ubicaciones anteriores.", icon: "undo-variant" }); router.back(); } catch (error) { void alert({ title: "No pudimos deshacer", message: error instanceof Error ? error.message : "Revise el estado de las prendas.", tone: "danger" }); } };

  if (result) return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.summary}><View style={styles.success}><MaterialCommunityIcons name="check-circle-outline" size={56} color={colors.success} /><Text style={styles.successTitle}>Traslado finalizado</Text><Text style={styles.summaryText}>{result.movedItems.length} prendas movidas a {result.destination.name}.</Text><Text style={styles.muted}>Puede deshacer este traslado hasta {new Date(result.expiresAt).toLocaleTimeString("es-MX", { hour: "2-digit", minute: "2-digit" })}.</Text></View><AppButton label="Deshacer traslado" icon="undo-variant" tone="secondary" onPress={() => void undo()} /><AppButton label="Ver destino" icon="map-marker-radius-outline" onPress={() => router.replace({ pathname: "/locations/[id]", params: { id: String(result.destination.id) } })} /><AppButton label="Ir al inicio" icon="home-outline" tone="quiet" onPress={() => router.replace("/")} /></ScrollView>;

  return <KeyboardAwareScreen contentContainerStyle={styles.content}><View style={styles.header}><View style={styles.step}><Text style={styles.stepNumber}>1</Text><View><Text style={styles.stepTitle}>Destino</Text><Text style={styles.muted}>{destination ? destination.name : "Escanee o seleccione una ubicación"}</Text></View></View>{destination ? <AppButton label="Cambiar" icon="swap-horizontal" tone="quiet" onPress={() => setDestination(null)} /> : null}</View>
    {!destination ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{locations.map((location) => <FilterChip key={location.id} label={location.name} selected={false} onPress={() => selectDestination(location)} />)}</ScrollView> : null}
    <View style={styles.cameraFrame}>{permission?.granted ? <CameraView style={StyleSheet.absoluteFill} facing="back" enableTorch={torch} onBarcodeScanned={busy ? undefined : ({ data }: BarcodeScanningResult) => void resolve(data)} barcodeScannerSettings={{ barcodeTypes: ["qr","code128","code39","ean13"] }} /> : <View style={styles.permission}><Text style={styles.muted}>Permita la cámara para escanear.</Text><AppButton label="Permitir cámara" icon="camera-outline" onPress={() => void requestPermission()} /></View>}<Pressable accessibilityRole="button" accessibilityLabel={torch ? "Apagar luz" : "Encender luz"} onPress={() => setTorch((value) => !value)} style={styles.torch}><MaterialCommunityIcons name={torch ? "flashlight-off" : "flashlight"} size={24} color={colors.onPrimary} /></Pressable></View>
    <View style={styles.manual}><TextInput value={manual} onChangeText={setManual} autoCapitalize="characters" placeholder={destination ? "Código de prenda" : "Código de ubicación"} placeholderTextColor={colors.textMuted} maxFontSizeMultiplier={1.4} style={styles.input} /><AppButton label="Agregar" icon="plus" onPress={() => void resolve(manual)} disabled={!manual.trim() || busy} /></View>
    <View style={styles.step}><Text style={styles.stepNumber}>2</Text><View><Text style={styles.stepTitle}>Prendas</Text><Text style={styles.counter}>{items.length} agregadas</Text></View></View>
    {lastItem ? <View style={styles.latest}><MaterialCommunityIcons name="hanger" size={28} color={colors.primary} /><View style={styles.latestCopy}><Text style={styles.latestTitle}>Última: {lastItem.code}</Text><Text style={styles.muted}>{formatMoney(lastItem.price)} · {lastItem.currentLocation?.name ?? "Sin asignar"}</Text></View></View> : null}
    <View style={styles.itemList}>{items.map((item) => <View key={item.id} style={styles.itemRow}><Text style={styles.itemCode}>{item.code}</Text><Text style={styles.muted}>{item.currentLocation?.name ?? "Sin asignar"}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Quitar ${item.code}`} onPress={() => setItems((current) => current.filter((candidate) => candidate.id !== item.id))} style={styles.remove}><MaterialCommunityIcons name="close" size={20} color={colors.danger} /></Pressable></View>)}</View>
    {rejections.length ? <View style={styles.rejections}><Text style={styles.rejectionTitle}>Lecturas rechazadas</Text>{rejections.slice(0,6).map((reason, index) => <Text key={`${reason}-${index}`} style={styles.rejection}>• {reason}</Text>)}</View> : null}
    <View style={styles.step}><Text style={styles.stepNumber}>3</Text><View><Text style={styles.stepTitle}>Confirmar</Text><Text style={styles.muted}>El traslado se aplica completo o no se aplica.</Text></View></View><AppButton label={busy ? "Finalizando..." : `Mover ${items.length} prendas`} icon="check-bold" onPress={() => void finish()} disabled={busy || !destination || items.length === 0} />
  </KeyboardAwareScreen>;
}

const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: 100, gap: spacing.md, backgroundColor: colors.canvas }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.md }, step: { flexDirection: "row", alignItems: "center", gap: spacing.md }, stepNumber: { width: 40, height: 40, paddingTop: 8, textAlign: "center", borderRadius: radius.pill, overflow: "hidden", color: colors.onPrimary, backgroundColor: colors.primary, fontSize: typography.title, fontWeight: "900" }, stepTitle: { color: colors.textPrimary, fontSize: typography.title, fontWeight: "900" }, muted: { color: colors.textMuted, lineHeight: 20 }, chips: { gap: spacing.sm }, cameraFrame: { height: 250, overflow: "hidden", borderRadius: radius.xl, backgroundColor: colors.dark }, permission: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.md, backgroundColor: colors.tint }, torch: { position: "absolute", top: spacing.sm, right: spacing.sm, width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: radius.pill, backgroundColor: colors.overlay }, manual: { flexDirection: "row", alignItems: "center", gap: spacing.sm }, input: { ...inputStyle, flex: 1 }, counter: { color: colors.success, fontWeight: "900" }, latest: { flexDirection: "row", alignItems: "center", gap: spacing.md, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.tint }, latestCopy: { flex: 1 }, latestTitle: { color: colors.textPrimary, fontWeight: "900" }, itemList: { gap: spacing.sm }, itemRow: { minHeight: 60, flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, itemCode: { flex: 1, color: colors.textPrimary, fontWeight: "900" }, remove: { width: 48, height: 48, alignItems: "center", justifyContent: "center" }, rejections: { gap: spacing.xs, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.dangerSoft }, rejectionTitle: { color: colors.danger, fontWeight: "900" }, rejection: { color: colors.danger, lineHeight: 19 }, summary: { flexGrow: 1, justifyContent: "center", gap: spacing.md, padding: spacing.xl, backgroundColor: colors.canvas }, success: { alignItems: "center", gap: spacing.sm, padding: spacing.xl, borderRadius: radius.xl, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, successTitle: { color: colors.textPrimary, fontSize: 28, fontWeight: "900" }, summaryText: { color: colors.textPrimary, fontSize: typography.body, lineHeight: 22, textAlign: "center" } });
